// Builds `dist/preview.html` from the real `dist/index.html`, so the page that is looked at is
// the page that ships — a hand-copied one drifts, and a missing element takes the whole script
// down with it.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const markup = readFileSync(join(here, "../dist/index.html"), "utf8")
  .replace("<title>Orochi</title>", "<title>Orochi — preview</title>")
  .replace(
    '<script type="module" src="app.js"></script>',
    '<script src="preview-data.js"></script>\n<script src="preview-files.js"></script>\n<script type="module" src="app.js"></script>',
  );
writeFileSync(join(here, "../dist/preview.html"), markup);

// The Files pane answers by folder and by file, which one fixed answer per command cannot do.
// Built from the same recording the page's tests read, so what is looked at is what is tested.
const files = readFileSync(join(here, "files.json"), "utf8");
writeFileSync(
  join(here, "../dist/preview-files.js"),
  `// Generated by tests/make-preview.mjs from tests/files.json.
(() => {
  const files = ${files.trim()};
  const base = window.__TAURI__.core.invoke;
  const read = (path) =>
    path === "README.md" ? files.markdown : path === "blob.bin" ? files.binary : files.text;
  window.__TAURI__.core.invoke = (name, args = {}) => {
    if (name === "tree_refresh") return Promise.resolve(files.refresh);
    if (name === "tree_list") return Promise.resolve(files[args.dir === "" ? "root" : args.dir] ?? []);
    if (name === "tree_read") return Promise.resolve(read(args.path));
    if (name === "tree_find") return Promise.resolve(files[args.by] ?? []);
    if (name === "open_path") return Promise.resolve(null);
    return base(name, args);
  };
})();
`,
);
console.log("preview.html built from index.html");
